spring.application.name=datavault

server.error.include-stacktrace=never

# --- Admin Credentials ---
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASS}

# --- PostgreSQL DataSource ---
spring.datasource.url=jdbc:postgresql://localhost:5433/datavault
spring.datasource.username=${POSTGRESQL_USER_NAME}
spring.datasource.password=${POSTGRESQL_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Flyway ---
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# --- JWT signing key configuration---
app.jwt.keystore=classpath:jwt.p12
app.jwt.storePassword=${JWT_KEY_PASS}
app.jwt.keyAlias=${JWT_KEY_ALIAS}
app.jwt.keyPassword=${JWT_KEY_PASS}
app.jwt.expirationMin=15

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=300MB

# --- OAuth2 GitHub client ---
spring.security.oauth2.client.registration.github.client-id=${OAUTH_GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${OAUTH_GITHUB_SECRET}
# Reads users basic GitHub profile (login, id, name, avatar, etc.) and email
spring.security.oauth2.client.registration.github.scope=read:user,user:email
spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8080/login/oauth2/code/github

# --- OAuth2 Google client ---
spring.security.oauth2.client.registration.google.client-id=${OAUTH_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${OAUTH_GOOGLE_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# --- Telegram bot ---
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.username=DataVaultReleaseBot


# --- AWS S3 ---
aws.s3.region=eu-north-1
aws.s3.bucket=kdsas-encrypted-files-s3-dev-381753457717-eu-north-1-an
aws.s3.access-key=${AWS_ACCESS_KEY_ID}
aws.s3.secret-key=${AWS_SECRET_ACCESS_KEY}

# --- Filebase S3-compatable IPFS ---
filebase.s3.endpoint=https://s3.filebase.io
filebase.s3.region=auto
filebase.s3.bucket=kdsas-encrypted-files-ipfs-dev
filebase.s3.access-key=${FILEBASE_ACCESS_KEY_ID}
filebase.s3.secret-key=${FILEBASE_SECRET_ACCESS_KEY}


audit.log.hmac-secret=${AUDIT_LOG_HMAC_SECRET}
